# kubernetes/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderproc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderproc
  template:
    metadata:
      labels:
        app: orderproc
    spec:
      containers:
      - name: orderproc
        image: santoshpagire/order_proc:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orderproc-service
spec:
  selector:
    app: orderproc
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
  type: LoadBalancer