# kubernetes/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatlog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatlog
  template:
    metadata:
      labels:
        app: productcatlog
    spec:
      containers:
      - name: productcatlog
        image: santoshpagire/product-catlog:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productcatlog-service
spec:
  selector:
    app: productcatlog
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
  type: LoadBalancer